### PR TITLE
Add Platform Release Marketing Template

### PR DESCRIPTION
**Pull request by Emily-Jiang**

### CODE REVIEW

**Comment by Emily-Jiang** [comment]
@debbiehoffman please review

**Comment by aeiras** [comment]
It looks good. I will merge it once @@debbiehoffman reviews it as well :)

**Review by aeiras — APPROVED** [review]
Thank you, Emily! 

Debbie, you are most welcomed to provide feedback at any time. 
The template is needed for MP. 5.

**Comment by aeiras** [comment]
@Emily-Jiang @ederks85 
The template is ready to be used :)

**Pull request merged**
